export const typePokemon = {
    poison:{
        ulrImg:"./type/poisonLabel.svg",
        color:"#A15AB1"
    },
    grass:{
        urlImg:"./type/grassLabel.svg",
        color:"#729F92"
    },
    fire:{
        urlImg:"./type/fireLabel.svg",
        color:"#EAAB7D"
    },
    flying:{
        urlImg:"./type/flyingLabel.svg",
        color:"#6892B0"
    },
    water:{
        urlImg:"./type/waterLabel.svg",
        color:"#71C3FF"
    },
    bug:{
        urlImg:"./type/bugLabel.svg",
        color:"#76A866"
    },
    normal:{
        urlImg:"./type/grassLabel.svg",
        color:"#BF9762"
    },
    dark:{
        urlImg:"./type/grassLabel.svg",
        color:"#5E4C4C"
    },
    dragon:{
        urlImg:"./type/dragonLabel.svg",
        color:"#004170"
    },
    electric:{
        urlImg:"./type/electricLabel.svg",
        color:"#FAD33E"
    },
    fairy:{
        urlImg:"./type/fairyLabel.svg",
        color:"#F9A8EF"
    },
    fighting:{
        urlImg:"./type/fightingLabel.svg",
        color:"#9B4840"
    },
    ghost:{
        urlImg:"./type/ghostLabel.svg",
        color:"#7D66AE"
    },
    ground:{
        urlImg:"./type/groundLabel.svg",
        color:"#C8AB63"
    },
    ice:{
        urlImg:"./type/iceLabel.svg",
        color:"#94E3F1"
    },
    psychic:{
        urlImg:"./type/psychicLabel.svg",
        color:"#F5779E"
    },
    rock:{
        urlImg:"./type/rockLabel.svg",
        color:"#A8865D"
    },
    steel:{
        urlImg:"./type/steelLabel.svg",
        color:"#ABA9BE"
    }
}