export const typePokemon = {
    poison:{
        valor:"poison",
        ulrImg:"./type/poisonLabel.svg",
        color:"#A15AB1"
    },
    grass:{
        valor:"grass",
        urlImg:"./type/grassLabel.svg",
        color:"#729F92"
    },
    fire:{
        valor:"fire",
        urlImg:"./type/fireLabel.svg",
        color:"#EAAB7D"
    },
    flying:{
        valor:"flying",
        urlImg:"./type/flyingLabel.svg",
        color:"#6892B0"
    },
    water:{
        valor:"water",
        urlImg:"./type/waterLabel.svg",
        color:"#71C3FF"
    },
    bug:{
        valor:"bug",
        urlImg:"./type/bugLabel.svg",
        color:"#76A866"
    },
    normal:{
        valor:"normal",
        urlImg:"./type/grassLabel.svg",
        color:"#BF9762"
    },
    dark:{
        valor:"dark",
        urlImg:"./type/grassLabel.svg",
        color:"#5E4C4C"
    },
    dragon:{
        valor:"dragon",
        urlImg:"./type/dragonLabel.svg",
        color:"#004170"
    },
    electric:{
        valor:"electric",
        urlImg:"./type/electricLabel.svg",
        color:"#FAD33E"
    },
    fairy:{
        valor:"fairy",
        urlImg:"./type/fairyLabel.svg",
        color:"#F9A8EF"
    },
    fighting:{
        valor:"fighting",
        urlImg:"./type/fightingLabel.svg",
        color:"#9B4840"
    },
    ghost:{
        valor:"ghost",
        urlImg:"./type/ghostLabel.svg",
        color:"#7D66AE"
    },
    ground:{
        valor:"ground",
        urlImg:"./type/groundLabel.svg",
        color:"#C8AB63"
    },
    ice:{
        valor:"ice",
        urlImg:"./type/iceLabel.svg",
        color:"#94E3F1"
    },
    psychic:{
        valor:"psychic",
        urlImg:"./type/psychicLabel.svg",
        color:"#F5779E"
    },
    rock:{
        valor:"rock",
        urlImg:"./type/rockLabel.svg",
        color:"#A8865D"
    },
    steel:{
        valor:"steel",
        urlImg:"./type/steelLabel.svg",
        color:"#ABA9BE"
    }
}