export const typePokemon = {
    poison:{
        ulrImg:"./type/poisonLabel.svg",
        color:"#AD61AE"
    },
    grass:{
        urlImg:"./type/grassLabel.svg",
        color:"#70B873"
    },
    fire:{
        urlImg:"./type/fireLabel.svg",
        color:"#F44900"
    },
    flying:{
        urlImg:"./type/flyingLabel.svg",
        color:"#6892B0"
    },
    water:{
        urlImg:"./type/waterLabel.svg",
        color:"#33A4F5"
    },
    bug:{
        urlImg:"./type/bugLabel.svg",
        color:"#316520"
    },
    normal:{
        urlImg:"./type/grassLabel.svg",
        color:"#5C5365"
    },
    dark:{
        urlImg:"./type/grassLabel.svg",
        color:"#5C5365"
    },
    dragon:{
        urlImg:"./type/dragonLabel.svg",
        color:"#F4D23B"
    },
    electric:{
        urlImg:"./type/electricLabel.svg",
        color:"#F4D23B"
    },
    fairy:{
        urlImg:"./type/fairyLabel.svg",
        color:"#EC8FE6"
    },
    fighting:{
        urlImg:"./type/fightingLabel.svg",
        color:"#CE4069"
    },
    ghost:{
        urlImg:"./type/ghostLabel.svg",
        color:"#5269AC"
    },
    ground:{
        urlImg:"./type/groundLabel.svg",
        color:"#D97745"
    },
    ice:{
        urlImg:"./type/iceLabel.svg",
        color:"#F67176"
    },
    pshychic:{
        urlImg:"./type/pshychicLabel.svg",
        color:"#F67176"
    },
    rock:{
        urlImg:"./type/rockLabel.svg",
        color:"#C7B78B"
    },
    steel:{
        urlImg:"./type/steelLabel.svg",
        color:"#BBBBBB"
    }
}